fix: use fresh expiry on request_status and read_state
dfinity/agent-rs pull request #109
Opened 2021-02-05 05:41 UTC by p-shahi

2021-02-05 19:26 UTC, ericswanson-dfinity commented on ic-agent/src/agent/mod.rs
> -                .request_status_raw(&request_id, self.ingress_expiry_datetime)
Is `self.ingress_expiry_datetime` something that we should remove altogether?

2021-02-05 19:29 UTC, ericswanson-dfinity approved these changes

2021-02-11 00:26 UTC, hansl requested changes

2021-02-11 00:26 UTC, hansl commented on ic-agent/Cargo.toml
> +[dependencies.delay]
Woah let's not get this in master.

2021-02-11 22:20 UTC, hansl approved these changes

2021-02-11 22:37 UTC, merged