feat: add ic-wasm to perform Wasm transformations for canister
dfinity/agent-rs pull request #328
Opened 2022-03-29 21:55 UTC by chenyan-dfinity

Part of https://dfinity.atlassian.net/browse/IC-1147

The library can be used to manage canister metadata. It can be called by dfx or as a standalone CLI tool. 

In the future, this library will also support other Wasm related features, such as canister profiling, code size reduction and inspection of IC system API.

2022-03-31 16:51 UTC, ericswanson-dfinity requested changes
Can we have a github workflow to build these?

2022-04-05 19:10 UTC, chenyan-dfinity commented
Moved to https://github.com/dfinity/ic-wasm

2022-04-05 19:10 UTC, closed without merging

2022-04-06 02:08 UTC, paulyoung commented
Is https://github.com/dfinity/ic-wasm private?

2022-04-06 02:10 UTC, chenyan-dfinity commented
Will be public soon.