chore: Release agent-rs 0.23.0
dfinity/agent-rs pull request #394
Opened 2022-12-01 23:37 UTC by adamspofford-dfinity

2022-12-01 23:58 UTC, ericswanson-dfinity commented on CHANGELOG.md
> +## [0.23.0] - 2022
```suggestion
## [0.23.0] - 2022-12-01
```

2022-12-01 23:59 UTC, ericswanson-dfinity requested changes

2022-12-01 23:59 UTC, ericswanson-dfinity commented on CHANGELOG.md
> +## [0.23.0] - 2022
```suggestion
## [0.23.0] - 2022-12-01
```

2022-12-02 00:45 UTC, adamspofford-dfinity commented on CHANGELOG.md
> +## [0.23.0] - 2022
Good old forgetting to save the file 😅

2022-12-02 03:50 UTC, ericswanson-dfinity approved these changes

2022-12-02 16:42 UTC, merged