fix: remove argument builder from ic-utils
dfinity/agent-rs pull request #465
Opened 2023-08-28 20:53 UTC by chenyan-dfinity

# Description

* Remove argument builder from ic-utils to prevent Send for candid::Type.

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

# Checklist:

- [ ] The title of this PR complies with [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/).
- [ ] I have edited the CHANGELOG accordingly.
- [ ] I have made corresponding changes to the documentation.

2023-08-28 23:30 UTC, adamspofford-dfinity requested changes
This entirely changes the semantics of the `with_arg` functions, making it impossible to pass multiple arguments and silently breaking any code that already does.

2023-08-29 00:08 UTC, chenyan-dfinity commented
@eric-swanson What do you think?

2023-08-29 00:37 UTC, ericswanson-dfinity commented
> @eric-swanson What do you think?

How about this?

Make `.with_arg()` report an error (either panic in `with_arg()`, or have `build()` return an error) if called more than once for a builder.  The error can tell what you should do ("`use CallBuilder::set_raw_arg(candid::Encode!(arg1, arg2)?)`") instead.

2023-08-29 00:39 UTC, chenyan-dfinity commented
Sounds good! Will do.

2023-08-29 01:00 UTC, ericswanson-dfinity commented
> Sounds good! Will do.

Are you satisfied with that @adamspofford-dfinity ?  The only other thing I can think of would be for `.with_arg` to return a Builder that doesn't have any of the argument-adding methods, in order to catch it at compile time.

2023-08-29 01:03 UTC, adamspofford-dfinity commented
I would like the alternative to be an ArgumentEncoder function the way `with_arg` is a CandidType function; a name that springs to mind is `with_args`. Otherwise, yes, that works.

2023-08-29 01:05 UTC, chenyan-dfinity commented
Sounds good.

2023-08-29 15:03 UTC, lwshang commented
> Reverts https://github.com/dfinity/agent-rs/pull/454
Will we be able to remove the `arg_type` feature of candid crate?

2023-08-29 15:04 UTC, chenyan-dfinity commented
> Will we be able to remove the arg_type feature of candid crate?

Yep

2023-08-30 16:37 UTC, adamspofford-dfinity commented on ic-utils/src/interfaces/wallet.rs
This should also have a with_args overload.

2023-08-30 16:37 UTC, adamspofford-dfinity commented on ic-utils/src/interfaces/management_canister/builders.rs
This should also have a with_args overload.

2023-08-30 18:32 UTC, chenyan-dfinity commented
PTAL

2023-08-30 18:47 UTC, ericswanson-dfinity commented on ic-utils/src/canister.rs
> +            panic!("argument is being set for more than once");
```suggestion
            panic!("argument is being set more than once");
```

2023-08-30 18:48 UTC, ericswanson-dfinity commented on ic-utils/src/canister.rs
> +            panic!("argument is being set for more than once");
```suggestion
            panic!("argument is being set more than once");
```

2023-08-30 19:25 UTC, adamspofford-dfinity approved these changes

2023-08-30 19:52 UTC, merged