feat: Round `ingress_expiry` to the minute
dfinity/agent-rs pull request #481
Opened 2023-10-10 19:25 UTC by adamspofford-dfinity

If the agent's configured ingress expiry duration is >1m, this rounds the ingress expiry *timestamp* to the closest minute (and otherwise, rounds down to the second). This will hopefully reduce cache misses, since a nanosecond difference in the ingress expiry timestamp means a different request ID and is thus uncacheable.

Implements SDK-1259.

2023-10-11 00:30 UTC, ericswanson-dfinity requested changes

2023-10-11 00:30 UTC, ericswanson-dfinity commented on ic-agent/src/agent/mod.rs
> +        };
It seems like we're unconditionally doing `.replace_nanosecond(0)`.  Could we do it in one place?

2023-10-11 17:41 UTC, ericswanson-dfinity approved these changes

2023-10-11 17:43 UTC, merged

2023-10-25 11:14 UTC, roelstorms commented on ic-agent/src/agent/mod.rs
> +        for _ in 0..6 {
Just out of curiosity, why aren't we using the iterator from the for loop instead of num_timestamps?

2023-10-25 13:10 UTC, roelstorms commented on ic-agent/src/agent/mod.rs
> +        if self.ingress_expiry.as_secs() > 60 {
Why is rounding only done if ingress_expiry is larger than 60 seconds? 
Is this aligned between the BN team (caching), agent-js and agent-rs?