chore: bump hyper to 1.0.1
dfinity/agent-rs pull request #527
Opened 2024-03-07 22:43 UTC by mraszyk

This PR bumps hyper to 1.0.1.

2024-03-07 23:15 UTC, adamspofford-dfinity commented
Is this prompted by something? Otherwise I would prefer to keep 0.14 until reqwest updates to hyper 1.0, so there is only one copy in the tree.

2024-03-08 08:52 UTC, mraszyk commented
> Is this prompted by something? Otherwise I would prefer to keep 0.14 until reqwest updates to hyper 1.0, so there is only one copy in the tree.

This blocks bumping axum to 0.7 in icx-proxy.

2024-03-08 21:29 UTC, mraszyk commented on ic-agent/Cargo.toml
> +hyper-util = { version = "0.1.3", features = ["client", "client-legacy", "http2"] }
What do you mean?

2024-03-08 21:31 UTC, mraszyk commented on ic-agent/Cargo.toml
> +hyper-util = { version = "0.1.3", features = ["client", "client-legacy", "http2"] }
I've added `optional = true` to all of them if that's what you mean.

2024-03-09 00:30 UTC, adamspofford-dfinity requested changes
This code does not build with `--features hyper`.

2024-03-09 00:31 UTC, adamspofford-dfinity commented on ic-agent/Cargo.toml
> +hyper-util = { version = "0.1.3", features = ["client", "client-legacy", "http2"] }
As in, they should only be enabled when the hyper feature is enabled.

2024-03-09 11:29 UTC, mraszyk commented on ic-agent/Cargo.toml
> +hyper-util = { version = "0.1.3", features = ["client", "client-legacy", "http2"] }
Is it ok now?

2024-03-09 11:30 UTC, mraszyk commented
> This code does not build with `--features hyper`.

What do you mean? The CI pipeline has succeeded and I could also successfully run `cargo build --release --features hyper` locally.

2024-03-11 14:55 UTC, adamspofford-dfinity commented
Apologies for not adding detail - the new errors look like this:
```
error[E0432]: unresolved import `http_body_to_bytes`
 --> ic-agent/src/agent/http_transport/hyper_transport.rs:7:5
  |
7 | use http_body_to_bytes::{http_body_to_bytes, http_body_to_bytes_with_max_length};
  |     ^^^^^^^^^^^^^^^^^^ use of undeclared crate or module `http_body_to_bytes`
```
Because the optional dependencies were not added to the hyper feature. I am not sure why it is succeeding on your local machine. I am fixing the CI to detect this in #528.

2024-03-11 18:40 UTC, mraszyk commented
I could reproduce the build failure and fixed it now.

2024-03-11 18:42 UTC, adamspofford-dfinity approved these changes

2024-03-11 18:57 UTC, merged